/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedOperationsWarehouseRouteImport } from './routes/_authenticated/operations.warehouse'
import { Route as AuthenticatedOperationsTruckingRouteImport } from './routes/_authenticated/operations.trucking'
import { Route as AuthenticatedOperationsSupplyChainRouteImport } from './routes/_authenticated/operations.supply-chain'
import { Route as AuthenticatedOperationsOceanRouteImport } from './routes/_authenticated/operations.ocean'
import { Route as AuthenticatedOperationsCustomsRouteImport } from './routes/_authenticated/operations.customs'
import { Route as AuthenticatedOperationsAirRouteImport } from './routes/_authenticated/operations.air'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsWarehouseRoute =
  AuthenticatedOperationsWarehouseRouteImport.update({
    id: '/operations/warehouse',
    path: '/operations/warehouse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsTruckingRoute =
  AuthenticatedOperationsTruckingRouteImport.update({
    id: '/operations/trucking',
    path: '/operations/trucking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsSupplyChainRoute =
  AuthenticatedOperationsSupplyChainRouteImport.update({
    id: '/operations/supply-chain',
    path: '/operations/supply-chain',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsOceanRoute =
  AuthenticatedOperationsOceanRouteImport.update({
    id: '/operations/ocean',
    path: '/operations/ocean',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsCustomsRoute =
  AuthenticatedOperationsCustomsRouteImport.update({
    id: '/operations/customs',
    path: '/operations/customs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperationsAirRoute =
  AuthenticatedOperationsAirRouteImport.update({
    id: '/operations/air',
    path: '/operations/air',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/research': typeof AuthenticatedResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/operations/air': typeof AuthenticatedOperationsAirRoute
  '/operations/customs': typeof AuthenticatedOperationsCustomsRoute
  '/operations/ocean': typeof AuthenticatedOperationsOceanRoute
  '/operations/supply-chain': typeof AuthenticatedOperationsSupplyChainRoute
  '/operations/trucking': typeof AuthenticatedOperationsTruckingRoute
  '/operations/warehouse': typeof AuthenticatedOperationsWarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email': typeof AuthenticatedEmailRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/research': typeof AuthenticatedResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/operations/air': typeof AuthenticatedOperationsAirRoute
  '/operations/customs': typeof AuthenticatedOperationsCustomsRoute
  '/operations/ocean': typeof AuthenticatedOperationsOceanRoute
  '/operations/supply-chain': typeof AuthenticatedOperationsSupplyChainRoute
  '/operations/trucking': typeof AuthenticatedOperationsTruckingRoute
  '/operations/warehouse': typeof AuthenticatedOperationsWarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/operations/air': typeof AuthenticatedOperationsAirRoute
  '/_authenticated/operations/customs': typeof AuthenticatedOperationsCustomsRoute
  '/_authenticated/operations/ocean': typeof AuthenticatedOperationsOceanRoute
  '/_authenticated/operations/supply-chain': typeof AuthenticatedOperationsSupplyChainRoute
  '/_authenticated/operations/trucking': typeof AuthenticatedOperationsTruckingRoute
  '/_authenticated/operations/warehouse': typeof AuthenticatedOperationsWarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/research'
    | '/api/chat'
    | '/chat/$threadId'
    | '/operations/air'
    | '/operations/customs'
    | '/operations/ocean'
    | '/operations/supply-chain'
    | '/operations/trucking'
    | '/operations/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/notes'
    | '/planner'
    | '/profile'
    | '/research'
    | '/api/chat'
    | '/chat/$threadId'
    | '/operations/air'
    | '/operations/customs'
    | '/operations/ocean'
    | '/operations/supply-chain'
    | '/operations/trucking'
    | '/operations/warehouse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/email'
    | '/_authenticated/notes'
    | '/_authenticated/planner'
    | '/_authenticated/profile'
    | '/_authenticated/research'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/operations/air'
    | '/_authenticated/operations/customs'
    | '/_authenticated/operations/ocean'
    | '/_authenticated/operations/supply-chain'
    | '/_authenticated/operations/trucking'
    | '/_authenticated/operations/warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/warehouse': {
      id: '/_authenticated/operations/warehouse'
      path: '/operations/warehouse'
      fullPath: '/operations/warehouse'
      preLoaderRoute: typeof AuthenticatedOperationsWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/trucking': {
      id: '/_authenticated/operations/trucking'
      path: '/operations/trucking'
      fullPath: '/operations/trucking'
      preLoaderRoute: typeof AuthenticatedOperationsTruckingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/supply-chain': {
      id: '/_authenticated/operations/supply-chain'
      path: '/operations/supply-chain'
      fullPath: '/operations/supply-chain'
      preLoaderRoute: typeof AuthenticatedOperationsSupplyChainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/ocean': {
      id: '/_authenticated/operations/ocean'
      path: '/operations/ocean'
      fullPath: '/operations/ocean'
      preLoaderRoute: typeof AuthenticatedOperationsOceanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/customs': {
      id: '/_authenticated/operations/customs'
      path: '/operations/customs'
      fullPath: '/operations/customs'
      preLoaderRoute: typeof AuthenticatedOperationsCustomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations/air': {
      id: '/_authenticated/operations/air'
      path: '/operations/air'
      fullPath: '/operations/air'
      preLoaderRoute: typeof AuthenticatedOperationsAirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedOperationsAirRoute: typeof AuthenticatedOperationsAirRoute
  AuthenticatedOperationsCustomsRoute: typeof AuthenticatedOperationsCustomsRoute
  AuthenticatedOperationsOceanRoute: typeof AuthenticatedOperationsOceanRoute
  AuthenticatedOperationsSupplyChainRoute: typeof AuthenticatedOperationsSupplyChainRoute
  AuthenticatedOperationsTruckingRoute: typeof AuthenticatedOperationsTruckingRoute
  AuthenticatedOperationsWarehouseRoute: typeof AuthenticatedOperationsWarehouseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedOperationsAirRoute: AuthenticatedOperationsAirRoute,
  AuthenticatedOperationsCustomsRoute: AuthenticatedOperationsCustomsRoute,
  AuthenticatedOperationsOceanRoute: AuthenticatedOperationsOceanRoute,
  AuthenticatedOperationsSupplyChainRoute:
    AuthenticatedOperationsSupplyChainRoute,
  AuthenticatedOperationsTruckingRoute: AuthenticatedOperationsTruckingRoute,
  AuthenticatedOperationsWarehouseRoute: AuthenticatedOperationsWarehouseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
